# Generated by Django 5.0.7 on 2024-07-31 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='sluf',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='slug',
            new_name='sluf',
        ),
    ]
