# Generated by Django 5.0.7 on 2024-07-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_slug_category_sluf_rename_slug_course_sluf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sluf',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='sluf',
            new_name='slug',
        ),
    ]
