# Generated by Django 5.0.7 on 2024-08-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
